import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer.";

const montse = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Monarca | Life Improvement",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
		<html lang="en">
			<body className={montse.className}>
				<Header />
				<div className="max-w-max m-auto overflow-hidden w-full">
					{children}
				</div>
        <Footer/>
			</body>
		</html>
	);
}
